Repository JNU-econovation/EEOS, pull requests merged in 2023-10, with the labels that each got.

#5 [FE] 스프린트 1
  FE/.gitignore
  FE/FE.md
  FE/app/globals.css
  FE/app/layout.tsx
  FE/app/page.tsx
  FE/components/common/Button.tsx
  FE/components/common/Tabs.tsx
  FE/components/common/Title.tsx
  FE/components/common/pagination/Pagination.tsx
  FE/components/common/pagination/PaginationItem.tsx
  FE/components/home/EventList.tsx
  FE/components/home/EventListItem.tsx
  FE/components/layout/DefaultLayout.tsx
  FE/components/layout/Header.tsx
  FE/components/layout/SubLayout.tsx
  FE/next.config.js
  FE/package.json
  FE/pnpm-lock.yaml
  FE/postcss.config.js
  FE/public/icons/calendar.svg
  FE/public/icons/check.svg
  FE/public/icons/left.svg
  FE/public/icons/pencil.svg
  FE/public/icons/plus.svg
  FE/public/icons/right.svg
  FE/public/icons/user.svg
  FE/public/icons/x.svg
  FE/src/apis/event/event.ts
  FE/src/apis/event/index.ts
  FE/src/apis/index.ts
  FE/src/constants/home.ts
  FE/src/types/home/home.ts
  FE/src/utils/calcPageNumbers.ts
  FE/src/utils/date.ts
  FE/src/utils/provider.tsx
  FE/tailwind.config.ts
  FE/tsconfig.json
Labels: FE, feature☁️

#13 [FEAT/ BE] 개발환경 세팅
  .github/PULL_REQUEST_TEMPLATE.md
  BE/eeos/.gitignore
  BE/eeos/build.gradle
  BE/eeos/gradle/wrapper/gradle-wrapper.jar
  BE/eeos/gradle/wrapper/gradle-wrapper.properties
  BE/eeos/gradlew
  BE/eeos/gradlew.bat
  BE/eeos/resources/local-develop-environment/docker-compose.yml
  BE/eeos/resources/local-develop-environment/mysql-init.d/00_init.sql
  BE/eeos/scripts/local-develop-env-reset
  BE/eeos/scripts/pre-commit
  BE/eeos/settings.gradle
  BE/eeos/src/main/java/com/blackcompany/eeos/EeosApplication.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/exception/BusinessException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/exception/GlobalExceptionHandler.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/persistence/BaseEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/persistence/SoftDeleteListener.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/presentation/respnose/ApiResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/presentation/respnose/ApiResponseBody.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/presentation/respnose/ApiResponseGenerator.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/presentation/respnose/MessageCode.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/presentation/respnose/PageResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/AbstractModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/converter/AbstractDtoConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/converter/AbstractEntityConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/converter/DateConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/dto/AbstractDto.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/dto/AbstractRequestDto.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/dto/AbstractResponseDto.java
  BE/eeos/src/main/java/com/blackcompany/eeos/config/MysqlConfig.java
  BE/eeos/src/main/resources/application-local-mysql.yml
  BE/eeos/src/main/resources/application.yml
  BE/eeos/src/test/java/com/blackcompany/eeos/EeosApplicationTests.java
  BE/eeos/tasks/formatting-task.gradle
  BE/eeos/tasks/install-git-hooks.gradle
Labels: BE, feature☁️

#18 [FEAT/BE] 프로그램 단 건 조회 구현
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/domain/ProgramModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/GetProgramResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/converter/ProgramResponseConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/exception/NotFoundProgramException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetProgramUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
Labels: BE, feature☁️

#22 [BE/FIX] API 문서에 맞게 변경
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/CommandProgramResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
Labels: BE, bug-fix🚨

#10 [FE] Create 페이지 구현
  FE/app/create/page.tsx
  FE/app/detail/[programId]/page.tsx
  FE/app/edit/page.tsx
  FE/app/page.tsx
  FE/components/common/Button.tsx
  FE/components/common/Input.tsx
  FE/components/common/Textarea.tsx
  FE/components/common/Title.tsx
  FE/components/common/pagination/Pagination.tsx
  FE/components/create/Calendar.component.tsx
  FE/components/create/EventCreateForm.tsx
  FE/components/create/calendar.css
  FE/components/detail/MemberList.tsx
  FE/components/detail/MemberListItem.tsx
  FE/components/detail/ProgramInfo.tsx
  FE/components/home/EventList.tsx
  FE/components/home/EventListItem.tsx
  FE/components/home/ProgramList.tsx
  FE/components/home/ProgramListItem.tsx
  FE/components/layout/DefaultLayout.tsx
  FE/components/layout/Header.tsx
  FE/components/layout/SubLayout.tsx
  FE/next.config.js
  FE/package.json
  FE/pnpm-lock.yaml
  FE/public/favicon.ico
  FE/public/text_logo.svg
  FE/src/apis/event/event.ts
  FE/src/apis/event/index.ts
  FE/src/apis/index.ts
  FE/src/apis/member/member.ts
  FE/src/apis/program/program.ts
  FE/src/apis/types/member.d.ts
  FE/src/apis/types/program.d.ts
  FE/src/constants/home.ts
  FE/src/hooks/useOutsideRef.ts
  FE/src/stores/create.ts
  FE/src/types/home/home.ts
  FE/src/utils/date.ts
  FE/tailwind.config.ts
Labels: FE, feature☁️

#12 [FE] Sprint 1
  FE/.gitignore
  FE/FE.md
  FE/app/create/page.tsx
  FE/app/detail/[programId]/page.tsx
  FE/app/edit/page.tsx
  FE/app/globals.css
  FE/app/layout.tsx
  FE/app/page.tsx
  FE/components/common/Button.tsx
  FE/components/common/Input.tsx
  FE/components/common/Tabs.tsx
  FE/components/common/Textarea.tsx
  FE/components/common/Title.tsx
  FE/components/common/pagination/Pagination.tsx
  FE/components/common/pagination/PaginationItem.tsx
  FE/components/create/Calendar.component.tsx
  FE/components/create/EventCreateForm.tsx
  FE/components/create/calendar.css
  FE/components/detail/MemberList.tsx
  FE/components/detail/MemberListItem.tsx
  FE/components/detail/ProgramInfo.tsx
  FE/components/home/ProgramList.tsx
  FE/components/home/ProgramListItem.tsx
  FE/components/layout/DefaultLayout.tsx
  FE/components/layout/Header.tsx
  FE/components/layout/SubLayout.tsx
  FE/next.config.js
  FE/package.json
  FE/pnpm-lock.yaml
  FE/postcss.config.js
  FE/public/favicon.ico
  FE/public/icons/calendar.svg
  FE/public/icons/check.svg
  FE/public/icons/left.svg
  FE/public/icons/pencil.svg
  FE/public/icons/plus.svg
  FE/public/icons/right.svg
  FE/public/icons/user.svg
  FE/public/icons/x.svg
  FE/public/text_logo.svg
  FE/src/apis/index.ts
  FE/src/apis/member/member.ts
  FE/src/apis/program/program.ts
  FE/src/apis/types/member.d.ts
  FE/src/apis/types/program.d.ts
  FE/src/constants/home.ts
  FE/src/hooks/useOutsideRef.ts
  FE/src/stores/create.ts
  FE/src/types/home/home.ts
  FE/src/utils/calcPageNumbers.ts
  FE/src/utils/date.ts
  FE/src/utils/provider.tsx
  FE/tailwind.config.ts
  FE/tsconfig.json
Labels: FE, feature☁️

#25 docs: 브랜치 전략 추가
  docs/브랜치 전략.md
Labels: document📄

#28 [FEAT] 프로그램 참석자 정보 가져오는 API 구현
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/dto/AttendInfoResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/dto/converter/AttendInfoConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/exception/NotFoundMemberException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/AttendModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/AttendStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/converter/AttendEntityConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/AttendService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/CandidateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/DefaultCandidateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/usecase/GetAttendantInfoUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/persistence/AttendEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/persistence/AttendRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/presentation/AttendController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/model/MemberModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/model/converter/MemberEntityConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/service/MemberService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/converter/ProgramResponseConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
Labels: BE, enhancement 🍀

#31 [FEAT/BE] 유저의 참셕/불참 구현
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/dto/ChangeStatusRequest.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/dto/converter/AttendInfoConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/exception/NotFoundAttendException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/exception/NotFoundStatusException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/AttendModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/AttendStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/converter/AttendEntityConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/AttendService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/usecase/ChangeStatusUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/persistence/AttendRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/presentation/AttendController.java
Labels: BE, enhancement 🍀

#35 [FE/FEAT] Detail 페이지 구현 & API 수정
  FE/.eslintrc.js
  FE/app/detail/[programId]/page.tsx
  FE/app/edit/[programId]/page.tsx
  FE/app/edit/page.tsx
  FE/components/common/Calendar.component.tsx
  FE/components/common/CheckBox.component.tsx
  FE/components/common/MarkdownEditor.component.tsx
  FE/components/common/Toggle.component.tsx
  FE/components/common/styles/calendar.css
  FE/components/common/styles/markdown-editor.styles.css
  FE/components/create/ProgramCreateForm.tsx
  FE/components/detail/MemberList.tsx
  FE/components/detail/MemberListItem.tsx
  FE/components/detail/ProgramInfo.tsx
  FE/components/edit/EditMemberList.component.tsx
  FE/components/edit/EditMemberListItem.component.tsx
  FE/components/edit/ProgramEditForm.tsx
  FE/components/layout/Header.tsx
  FE/next.config.js
  FE/package.json
  FE/pnpm-lock.yaml
  FE/postcss.config.js
  FE/src/apis/member/member.ts
  FE/src/apis/program/program.ts
  FE/src/stores/create.ts
  FE/src/utils/sort.ts
  FE/tailwind.config.ts
  FE/tsconfig.json
  docs/브랜치 전략.md
Labels: FE, bug-fix🚨, feature☁️

#43 [FEAT] 특정 유저 정보 가져오는 API 구현
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/dto/converter/AttendInfoConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/exception/NotSameBeforeStatusException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/AttendModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/AttendStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/AttendService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/usecase/GetAttendantInfoUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/presentation/AttendController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/exception/NotFoundProgramException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramValidService.java
Labels: BE, feature☁️

#44 [FEAT] dev 환경을 위한 더미 데이터 삽입
  BE/eeos/Dockerfile
  BE/eeos/docker-compose.yml
  BE/eeos/resources/local-develop-environment/mysql-init.d/01_create_table.sql
  BE/eeos/resources/local-develop-environment/mysql-init.d/02_add.data.sql
Labels: BE, feature☁️
