Repository JNU-econovation/EEOS, pull requests merged in 2023-11, with the labels that each got.

#47 [AOS/FEAT] init-project
  .idea/.gitignore
  .idea/black-company.iml
  .idea/modules.xml
  .idea/vcs.xml
  AOS/.gitignore
  AOS/.idea/.name
  AOS/.idea/compiler.xml
  AOS/.idea/gradle.xml
  AOS/.idea/kotlinc.xml
  AOS/.idea/misc.xml
  AOS/.idea/shelf/Changes.xml
  AOS/.idea/shelf/Changes/shelved.patch
  AOS/.idea/vcs.xml
  AOS/app/.gitignore
  AOS/app/build.gradle
  AOS/app/proguard-rules.pro
  AOS/app/src/androidTest/java/com/example/eeos/ExampleInstrumentedTest.kt
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/com/example/eeos/MainActivity.kt
  AOS/app/src/main/java/com/example/eeos/ui/theme/Color.kt
  AOS/app/src/main/java/com/example/eeos/ui/theme/Theme.kt
  AOS/app/src/main/java/com/example/eeos/ui/theme/Type.kt
  AOS/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  AOS/app/src/main/res/drawable/ic_launcher_background.xml
  AOS/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  AOS/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  AOS/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/values/colors.xml
  AOS/app/src/main/res/values/strings.xml
  AOS/app/src/main/res/values/themes.xml
  AOS/app/src/main/res/xml/backup_rules.xml
  AOS/app/src/main/res/xml/data_extraction_rules.xml
  AOS/app/src/test/java/com/example/eeos/ExampleUnitTest.kt
  AOS/build.gradle
  AOS/gradle.properties
  AOS/gradle/wrapper/gradle-wrapper.jar
  AOS/gradle/wrapper/gradle-wrapper.properties
  AOS/gradlew
  AOS/gradlew.bat
  AOS/settings.gradle
Labels: AOS, feature☁️, setting ⚙️

#53 [BE/FIX] column 에러 해결
  BE/eeos/src/main/java/com/blackcompany/eeos/program/persistence/ProgramEntity.java
Labels: BE, bug-fix🚨

#57 [BE/FIX] dev 서버 목 데이터 문제 해결
  BE/eeos/resources/local-develop-environment/docker-compose.yml
  BE/eeos/resources/local-develop-environment/mysql-init.d/01_create_table.sql
Labels: BE, bug-fix🚨

#49 [FE/REFACT] Term1 내용 리팩토링
  FE/app/detail/[programId]/page.tsx
  FE/app/globals.css
  FE/app/layout.tsx
  FE/app/not-found.tsx
  FE/app/page.tsx
  FE/components/common/Button.component.tsx
  FE/components/common/MarkdownEditor.component.tsx
  FE/components/common/form/LabeledInput.component.tsx
  FE/components/common/form/ProgramForm.component.tsx
  FE/components/common/pagination/Pagination.component.tsx
  FE/components/create/ProgramCreateForm.component.tsx
  FE/components/detail/MemberList.component.tsx
  FE/components/detail/ProgramInfo.component.tsx
  FE/components/edit/EditMemberList.component.tsx
  FE/components/edit/EditMemberListItem.component.tsx
  FE/components/edit/ProgramEditForm.component.tsx
  FE/components/home/ProgramListItem.tsx
  FE/components/layout/DefaultLayout.tsx
  FE/components/layout/Header.tsx
  FE/components/layout/SubLayout.tsx
  FE/package.json
  FE/pnpm-lock.yaml
  FE/src/apis/member.ts
  FE/src/apis/member/member.ts
  FE/src/apis/program.ts
  FE/src/apis/program/program.ts
  FE/src/apis/types/member.d.ts
  FE/src/constants/API.ts
  FE/src/constants/FORM_INFO.ts
  FE/src/constants/ROUTES.ts
  FE/src/stores/create.ts
  FE/src/utils/localStorage.ts
Labels: FE, refactor♻️

#62 [FE/FIX] API 수정사항 적용 및 버그 수정
  FE/app/page.tsx
  FE/components/detail/MemberList.component.tsx
  FE/components/detail/MemberListItem.component.tsx
  FE/components/detail/ProgramInfo.component.tsx
  FE/components/edit/EditMemberList.component.tsx
  FE/components/edit/EditMemberListItem.component.tsx
  FE/src/apis/member.ts
  FE/src/apis/program.ts
  FE/src/apis/types/member.d.ts
  FE/src/apis/types/program.d.ts
  FE/src/constants/API.ts
  FE/src/constants/home.ts
  FE/src/types/home/home.ts
  FE/src/utils/sort.ts
Labels: FE, bug-fix🚨

#64 [AOS/FEAT] 컴포넌트 구현
  .github/workflows/eeos-android-ci.yml
  AOS/app/src/main/java/com/example/eeos/ui/common/MemberInfo.kt
  AOS/app/src/main/java/com/example/eeos/ui/detail/MemberData.kt
  AOS/app/src/main/java/com/example/eeos/ui/detail/MemberList.kt
  AOS/app/src/main/java/com/example/eeos/ui/detail/ProgramDetail.kt
  AOS/app/src/main/java/com/example/eeos/ui/home/Program.kt
  AOS/app/src/main/java/com/example/eeos/ui/home/ProgramData.kt
  AOS/app/src/main/java/com/example/eeos/ui/home/TagChips.kt
  AOS/app/src/main/java/com/example/eeos/ui/theme/Theme.kt
  AOS/app/src/main/java/com/example/eeos/ui/theme/Type.kt
  AOS/app/src/main/res/drawable/common_logo.xml
  AOS/app/src/main/res/drawable/common_mypage_button.xml
  AOS/app/src/main/res/drawable/detail_ic_absent_20dp.xml
  AOS/app/src/main/res/drawable/detail_ic_attend_20dp.xml
  AOS/app/src/main/res/drawable/intro_logo_default.xml
  AOS/app/src/main/res/drawable/login_button.xml
  AOS/app/src/main/res/font/pretendard_black.ttf
  AOS/app/src/main/res/font/pretendard_bold.ttf
  AOS/app/src/main/res/font/pretendard_extrabold.ttf
  AOS/app/src/main/res/font/pretendard_extralight.ttf
  AOS/app/src/main/res/font/pretendard_light.ttf
  AOS/app/src/main/res/font/pretendard_medium.ttf
  AOS/app/src/main/res/font/pretendard_regular.ttf
  AOS/app/src/main/res/font/pretendard_semibold.ttf
  AOS/app/src/main/res/font/pretendard_thin.ttf
  AOS/app/src/main/res/values/colors.xml
  AOS/app/src/main/res/values/strings.xml
Labels: AOS, feature☁️

#65 hot-fix: 참석자 출석 업데이트 로직 수정
  FE/components/edit/EditMemberListItem.component.tsx
Labels: bug-fix🚨

#69 [FE/FEAT] UI 변경된 디자인 적용
  FE/app/create/page.tsx
  FE/app/detail/[programId]/page.tsx
  FE/app/edit/[programId]/page.tsx
  FE/app/globals.css
  FE/app/not-found.tsx
  FE/components/common/CheckBox.component.tsx
  FE/components/common/LoadingSpinner.tsx
  FE/components/common/Tabs.component.tsx
  FE/components/common/form/LabeledInput.component.tsx
  FE/components/common/toggle/CustomToggleItem.component.tsx
  FE/components/common/toggle/MultiToggle.component.tsx
  FE/components/common/toggle/Toggle.component.tsx
  FE/components/detail/MemberList.component.tsx
  FE/components/detail/MemberListItem.component.tsx
  FE/components/detail/ProgramInfo.component.tsx
  FE/components/edit/EditMemberList.component.tsx
  FE/components/edit/EditMemberListItem.component.tsx
  FE/components/home/ProgramListItem.tsx
  FE/components/layout/DefaultLayout.tsx
  FE/components/layout/Header.tsx
  FE/components/layout/SubLayout.tsx
  FE/public/eeos_logo.svg
  FE/public/icons/clock.svg
  FE/public/icons/minus.svg
  FE/public/icons/user.svg
  FE/src/apis/types/member.d.ts
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/types/common/common.ts
  FE/tailwind.config.ts
Labels: FE, feature☁️

#70 [FE/FEAT] 공통 컴포넌트 구현
  FE/components/common/CustomTabItem.tsx
  FE/components/common/Toggle.component.tsx
  FE/components/common/attendStatus/AttendStatusBadge.component.tsx
  FE/components/common/attendStatus/AttendStatusSelector.component.tsx
  FE/components/common/toggle/CustomToggleItem.component.tsx
  FE/components/edit/EditMemberListItem.component.tsx
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/types/common/common.ts
Labels: FE, feature☁️

#80 [FE] Term2 - Sprint1
  FE/app/create/page.tsx
  FE/app/detail/[programId]/page.tsx
  FE/app/edit/[programId]/page.tsx
  FE/app/globals.css
  FE/app/not-found.tsx
  FE/components/common/CheckBox.component.tsx
  FE/components/common/CustomTabItem.tsx
  FE/components/common/LoadingSpinner.tsx
  FE/components/common/Tabs.component.tsx
  FE/components/common/attendStatus/AttendStatusBadge.component.tsx
  FE/components/common/attendStatus/AttendStatusSelector.component.tsx
  FE/components/common/form/LabeledInput.component.tsx
  FE/components/detail/MemberList.component.tsx
  FE/components/detail/MemberListItem.component.tsx
  FE/components/detail/ProgramInfo.component.tsx
  FE/components/edit/EditMemberList.component.tsx
  FE/components/edit/EditMemberListItem.component.tsx
  FE/components/home/ProgramListItem.tsx
  FE/components/layout/DefaultLayout.tsx
  FE/components/layout/Header.tsx
  FE/components/layout/SubLayout.tsx
  FE/public/eeos_logo.svg
  FE/public/icons/clock.svg
  FE/public/icons/minus.svg
  FE/public/icons/user.svg
  FE/src/apis/types/member.d.ts
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/types/common/common.ts
  FE/tailwind.config.ts
Labels: FE

#83 [FE/FEAT] Detail 페이지 UI 개발
  FE/app/detail/[programId]/page.tsx
  FE/components/common/CustomTabItem.tsx
  FE/components/detail/EditAttendStatusModal.component.tsx
  FE/components/detail/ProgramInfo.component.tsx
  FE/components/layout/Header.tsx
  FE/tailwind.config.ts
Labels: FE, feature☁️

#89 [FE/FEAT] Header UI 구현 및 상수 형식 통일
  FE/app/edit/[programId]/page.tsx
  FE/components/common/CustomTabItem.tsx
  FE/components/common/attendStatus/AttendStatusSelector.component.tsx
  FE/components/common/form/ProgramForm.component.tsx
  FE/components/common/memberTable/MemberTable.component.tsx
  FE/components/common/memberTable/MemberTableItem.component.tsx
  FE/components/create/ProgramCreateForm.component.tsx
  FE/components/detail/EditAttendStatusModal.component.tsx
  FE/components/detail/MemberList.component.tsx
  FE/components/edit/ProgramEditForm.component.tsx
  FE/components/layout/ActiveStatusTab.component.tsx
  FE/components/layout/Header.tsx
  FE/components/layout/UserInfoModal.component.tsx
  FE/src/constants/ACTIVE_STATUS.ts
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/types/common/common.ts
Labels: FE, feature☁️

#96 [BE/BUG] 타임존 문제 해결
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/resources/application-local-mysql.yml
Labels: BE, bug-fix🚨

#98 [BE] Term2 - Sprint2
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/resources/application-local-mysql.yml
Labels: BE, sprint 💨

#99 [FE] Term2 - Sprint2
  FE/app/create/page.tsx
  FE/app/detail/[programId]/page.tsx
  FE/app/edit/[programId]/page.tsx
  FE/app/page.tsx
  FE/components/common/CustomTabItem.tsx
  FE/components/common/MarkdownEditor.component.tsx
  FE/components/common/attendStatus/AttendStatusSelector.component.tsx
  FE/components/common/form/FormButton.component.tsx
  FE/components/common/form/LabeledInput.component.tsx
  FE/components/common/form/ProgramCategoryTab.component.tsx
  FE/components/common/form/ProgramDateInput.component.tsx
  FE/components/common/form/ProgramForm.component.tsx
  FE/components/common/form/ProgramTitleAndDemandInput.component.tsx
  FE/components/common/markdown/MarkdownEditor.component.tsx
  FE/components/common/markdown/MarkdownEditorTab.component.tsx
  FE/components/common/markdown/MarkdownViewer.component.tsx
  FE/components/common/memberTable/ActiveStatusTab.component.tsx
  FE/components/common/memberTable/MemberTable.component.tsx
  FE/components/common/memberTable/MemberTableItem.component.tsx
  FE/components/create/ProgramCreateForm.component.tsx
  FE/components/detail/EditAttendStatusModal.component.tsx
  FE/components/detail/MemberList.component.tsx
  FE/components/detail/MemberListItem.component.tsx
  FE/components/detail/ProgramInfo.component.tsx
  FE/components/edit/EditMemberList.component.tsx
  FE/components/edit/EditMemberListItem.component.tsx
  FE/components/edit/ProgramEditForm.component.tsx
  FE/components/home/ProgramCategoryTab.component.tsx
  FE/components/layout/ActiveStatusTab.component.tsx
  FE/components/layout/DefaultLayout.tsx
  FE/components/layout/Header.tsx
  FE/components/layout/UserInfoModal.component.tsx
  FE/package.json
  FE/pnpm-lock.yaml
  FE/src/apis/types/member.d.ts
  FE/src/constants/ACTIVE_STATUS.ts
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/constants/PROGRAM.ts
  FE/src/types/common/common.ts
  FE/src/utils/sort.ts
  FE/tailwind.config.ts
Labels: FE, sprint 💨

#104 [BE/FIX] 조회 조건 추가
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/converter/DateConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/utils/DateConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/health/HealthController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/domain/ProgramModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/domain/ProgramStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/model/converter/ProgramRequestConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ActiveProgramStateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/EndProgramStateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramStateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/support/ProgramStatusFactory.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetProgramsUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/persistence/ProgramRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/presentation/annotation/OverDateValidator.java
Labels: BE, bug-fix🚨

#105 [FE/FEAT] API 요청 구현
  FE/components/common/form/ProgramForm.component.tsx
  FE/components/common/memberTable/MemberTable.component.tsx
  FE/components/common/memberTable/MemberTableItem.component.tsx
  FE/components/create/ProgramCreateForm.component.tsx
  FE/components/detail/MemberList.component.tsx
  FE/src/apis/member.ts
  FE/src/apis/members.ts
  FE/src/apis/program.ts
  FE/src/apis/types/member.d.ts
  FE/src/apis/types/program.d.ts
  FE/src/apis/user.ts
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/types/common/common.ts
  FE/src/types/member.ts
  FE/src/types/program.ts
Labels: FE, feature☁️

#107 [BE/BUG] term1 오류 해결
  BE/eeos/src/main/java/com/blackcompany/eeos/common/support/converter/DateConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/utils/DateConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/health/HealthController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/domain/ProgramModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/domain/ProgramStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/model/converter/ProgramRequestConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ActiveProgramStateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/EndProgramStateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramStateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/support/ProgramStatusFactory.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetProgramsUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/persistence/ProgramRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/presentation/annotation/OverDateValidator.java
Labels: BE, bug-fix🚨

#109 [FE/FEAT] API 요청 구현
  FE/components/common/form/ProgramForm.component.tsx
  FE/components/common/memberTable/MemberTable.component.tsx
  FE/components/common/memberTable/MemberTableItem.component.tsx
  FE/components/create/ProgramCreateForm.component.tsx
  FE/components/detail/MemberList.component.tsx
  FE/src/apis/member.ts
  FE/src/apis/members.ts
  FE/src/apis/program.ts
  FE/src/apis/types/member.d.ts
  FE/src/apis/types/program.d.ts
  FE/src/apis/user.ts
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/types/common/common.ts
  FE/src/types/member.ts
  FE/src/types/program.ts
Labels: FE, feature☁️

#111 [FE/FEAT] DTO 적용
  FE/src/apis/dtos/member.dto.ts
  FE/src/apis/dtos/program.dto.ts
  FE/src/apis/dtos/user.dto.ts
Labels: FE, feature☁️

#118 [BE/BUG] 환경별 cors 설정
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/java/com/blackcompany/eeos/config/WebMvcConfig.java
  BE/eeos/src/main/resources/application-dev-api.yml
  BE/eeos/src/main/resources/application-local-api.yml
  BE/eeos/src/main/resources/application-prod-api.yml
  BE/eeos/src/main/resources/application.yml
Labels: BE, bug-fix🚨

#119 [BE/BUG] term1 환경별 cors 설정
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/java/com/blackcompany/eeos/config/WebMvcConfig.java
  BE/eeos/src/main/resources/application-dev-api.yml
  BE/eeos/src/main/resources/application-local-api.yml
  BE/eeos/src/main/resources/application-prod-api.yml
  BE/eeos/src/main/resources/application.yml
Labels: BE, bug-fix🚨

#122 [BE/BUG] docker service 명 변경으로 인한 수정
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/java/com/blackcompany/eeos/common/utils/DateConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/health/HealthController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/domain/ProgramModel.java
  BE/eeos/src/main/resources/application-prod-mysql.yml
Labels: BE, bug-fix🚨

#123 [BE/BUG] term1 prod용 환경 설정으로 인한 변경
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/java/com/blackcompany/eeos/common/utils/DateConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/health/HealthController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/domain/ProgramModel.java
  BE/eeos/src/main/resources/application-prod-mysql.yml
Labels: BE, bug-fix🚨
