Repository JNU-econovation/EEOS, pull requests merged in 2024-02, with the labels that each got.

#237 [FE/FEAT] 반응형 적용
  FE/package.json
  FE/pnpm-lock.yaml
  FE/src/app/(auth)/layout.tsx
  FE/src/app/(auth)/login/page.tsx
  FE/src/app/(private)/(program)/detail/[programId]/page.tsx
  FE/src/app/(private)/(program)/layout.tsx
  FE/src/app/globals.css
  FE/src/app/layout.tsx
  FE/src/components/common/Title.tsx
  FE/src/components/common/form/ProgramForm.tsx
  FE/src/components/common/header/CreateBtn.tsx
  FE/src/components/common/header/Header.tsx
  FE/src/components/common/header/Modal/UserActiveModal.tsx
  FE/src/components/common/header/UserBtn.tsx
  FE/src/components/common/markdown/MarkdownEditor.tsx
  FE/src/components/common/markdown/MarkdownViewer.tsx
  FE/src/components/common/memberTable/MemberTable.tsx
  FE/src/components/common/memberTable/MemberTableHeader.tsx
  FE/src/components/common/pagination/Pagination.tsx
  FE/src/components/common/pagination/PaginationItem.tsx
  FE/src/components/common/tabs/Tab.tsx
  FE/src/components/login/LeftSection.tsx
  FE/src/components/login/RightSection.tsx
  FE/src/components/main/ProgramListItem.tsx
  FE/src/components/programCreate/CreateMemberTableItem.tsx
  FE/src/components/programDetail/program/EditAndDeleteButton.tsx
  FE/src/components/programDetail/program/ProgramHeader.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.container.tsx
  FE/src/components/programEdit/EditMemberTableItem.tsx
  FE/tailwind.config.ts
Labels: FE, feature☁️

#238 [FE/FEAT] 반응형 추가 적용 및 console 경고 해결
  FE/src/components/common/CheckBox.tsx
  FE/src/components/common/attendStatusToggle/AttendStatusToggleItem.tsx
  FE/src/components/common/form/LabeledInput.tsx
  FE/src/components/common/header/UserBtn.tsx
  FE/src/components/programDetail/attendee/MemberList.tsx
  FE/src/components/programDetail/attendee/MemberListItem.tsx
Labels: FE, bug-fix🚨, feature☁️

#242 docs: 엔드포인트 및 변수 명 변경
  AI/model.py
Labels: AI

#236 [BE/REFACTOR] actuator를 활용한 health check
  .github/workflows/backend-ci.yml
  BE/eeos/build.gradle
  BE/eeos/src/main/resources/application-actuator.yml
  BE/eeos/src/main/resources/application.yml
  BE/eeos/src/test/resources/application-test-api.yml
  BE/eeos/src/test/resources/application-test-mysql.yml
  BE/eeos/src/test/resources/application-test-oauth.yml
  BE/eeos/src/test/resources/application-test-token.yml
  BE/eeos/src/test/resources/application.yml
Labels: BE, enhancement 🍀

#259 [BE/FIX] 통과하지 못 하는 테스트를 통과시킨다.
  .github/workflows/backend-ci.yml
  BE/eeos/resources/test-develop-environment/docker-compose.yml
  BE/eeos/resources/test-develop-environment/mysql-init.d/00_init.sql
  BE/eeos/scripts/pre-commit
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/presentation/support/CookieTokenExtractor.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/model/ActiveStatus.java
  BE/eeos/src/test/java/com/blackcompany/eeos/attend/application/service/AttendServiceTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/attend/application/service/SelectAttendTargetServiceTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/attend/application/service/SelectTargetServiceTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/attend/application/service/SelectTeamBuildingTargetServiceTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/attend/fixture/AttendFixture.java
  BE/eeos/src/test/java/com/blackcompany/eeos/attend/fixture/FakeAttend.java
  BE/eeos/src/test/java/com/blackcompany/eeos/auth/application/domain/client/OauthMemberClientCompositeTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/auth/application/service/AuthFacadeServiceTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/auth/application/service/AuthServiceTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/auth/fixture/FakeMember.java
  BE/eeos/src/test/java/com/blackcompany/eeos/auth/fixture/FakeSlackApiClientFixture.java
  BE/eeos/src/test/java/com/blackcompany/eeos/auth/infra/oauth/slack/client/FakeSlackApiClient.java
  BE/eeos/src/test/java/com/blackcompany/eeos/auth/infra/oauth/slack/client/SlackOauthMemberClientTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/auth/presentation/support/CookieTokenExtractorTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/member/application/model/ActiveStatusTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/member/application/model/MemberModelTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/member/fixture/FakeMember.java
  BE/eeos/src/test/java/com/blackcompany/eeos/member/fixture/MemberFixture.java
  BE/eeos/src/test/java/com/blackcompany/eeos/program/application/event/DeletedProgramEventListenerTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/program/persistence/ProgramCategoryTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/program/presentation/ProgramControllerTest.java
  BE/eeos/src/test/resources/application-test-mysql.yml
Labels: BE, bug-fix🚨

#265 [BE/FEAT] 팀빌딩을 종료한다.
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/exception/DeniedEditTeamBuilding.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/exception/NotFoundProgressTeamBuildingException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/model/RestrictTeamBuilding.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/model/TeamBuildingModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/service/CommandTeamBuildingService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/usecase/EndTeamBuildingUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/persistence/TeamBuildingRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/presentation/TeamBuildingController.java
  BE/eeos/src/test/java/com/blackcompany/eeos/teamBuilding/application/model/TeamBuildingModelTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/teamBuilding/application/service/CommandTeamBuildingServiceTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/teamBuilding/fixture/TeamBuildingFixture.java
Labels: BE, feature☁️

#270 [BE/FEAT] 팀빌딩 완료 시 AI 서버에게 요청하기 구현
  BE/eeos/src/main/java/com/blackcompany/eeos/common/persistence/IntegerArrayConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/target/application/service/CommandAttendTeamBuildingService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/target/application/service/QueryTeamBuildingTargetService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/target/persistence/TeamBuildingTargetRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/dto/EachMemberResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/dto/ResultTeamBuildingResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/dto/converter/ResultTeamBuildingResponseConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/exception/NotFoundResultException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/model/RestrictTeamBuildingModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/model/TeamBuildingAccessRights.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/model/TeamBuildingModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/model/converter/TeamBuildingEntityConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/model/converter/TeamBuildingResultConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/service/CommandTeamBuildingService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/service/TeamBuildingService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/usecase/CompleteTeamBuildingUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/usecase/GetResultTeamBuildingUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/infra/client/ClusteringTeamApiClient.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/infra/client/ClusteringTeamApiClientImpl.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/infra/dto/ClusteringResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/infra/dto/ParticipantRequest.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/infra/dto/converter/ParticipantRequestConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/persistence/TeamBuildingResultEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/persistence/TeamBuildingResultRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/persistence/TeamBuildingStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/presentation/TeamBuildingController.java
  BE/eeos/src/test/java/com/blackcompany/eeos/teamBuilding/application/service/TeamBuildingServiceTest.java
Labels: BE, feature☁️

#274 [BE/FIX] 개발용 서버에서 발생한 오류를 해결합니다.
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/java/com/blackcompany/eeos/target/application/dto/QueryTargetInfoResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/target/application/service/AttendTeamBuildingService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/target/application/usecase/GetTargetInfoUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/target/presentation/TeamBuildingTargetController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/exception/CompleteTeamBuildingException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/exception/EndTeamBuildingException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/exception/NotFoundProgressTeamBuildingException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/service/JoinableValidateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/service/TeamBuildingService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/usecase/GetTeamBuildingUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/application/usecase/QueryTeamBuildingResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/persistence/TeamBuildingRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/teamBuilding/presentation/TeamBuildingController.java
  BE/eeos/src/main/resources/db/migration/V03__add_teambuilding_table.sql
  BE/eeos/src/main/resources/db/migration/V04__add_teambuilding_inital_table.sql
Labels: BE, bug-fix🚨

#281 [FE/FEAT] 팀빌딩 삭제 기능 구현
  FE/src/apis/teamBuilding.ts
  FE/src/components/teamBuildingDetail/teamBuilding/TeamBuildingHeader.tsx
  FE/src/constants/API.ts
  FE/src/hooks/query/useTeamBuildingQuery.ts
Labels: FE, feature☁️

#282 [BE/FIX] 별도의 트랜젝션으로 실행하도록 트랜젝션 분리
  BE/eeos/src/main/java/com/blackcompany/eeos/target/application/service/QueryTeamBuildingTargetService.java
Labels: BE, bug-fix🚨

#283 [FE/FEAT] 팀빌딩 삭제 기능 구현
  FE/src/apis/teamBuilding.ts
  FE/src/components/teamBuildingDetail/teamBuilding/TeamBuildingHeader.tsx
  FE/src/constants/API.ts
  FE/src/hooks/query/useTeamBuildingQuery.ts
Labels: FE, feature☁️

#287 [DOCS/AOS] 안드로이드 리드미 파일 작성
  AOS/AOS-README.md
  AOS/AOS.md
Labels: AOS, document📄

#288 [AOS/REFACTOR] ApiResponse 적용
  AOS/README.md
  AOS/app/build.gradle
  AOS/app/src/main/java/com/example/eeos/consts/Consts.kt
  AOS/app/src/main/java/com/example/eeos/consts/ErrorCode.kt
  AOS/app/src/main/java/com/example/eeos/data/repository/InfoRepositoryImpl.kt
  AOS/app/src/main/java/com/example/eeos/data/service/InfoService.kt
  AOS/app/src/main/java/com/example/eeos/data/source/InfoDataSource.kt
  AOS/app/src/main/java/com/example/eeos/domain/repository/InfoRepository.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavGraph.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetail.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetailViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/TopAppBarViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/util/GetErrorCode.kt
Labels: AOS, feature☁️, refactor♻️

#292 [BE/DOCS] README를 적용한다.
  BE/README.md
Labels: BE, document📄

#295 [AOS] merge to main
  AOS/.gitignore
  AOS/.idea/deploymentTargetDropDown.xml
  AOS/AOS.md
  AOS/README.md
  AOS/app/build.gradle
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/com/example/eeos/consts/Consts.kt
  AOS/app/src/main/java/com/example/eeos/consts/ErrorCode.kt
  AOS/app/src/main/java/com/example/eeos/data/repository/InfoRepositoryImpl.kt
  AOS/app/src/main/java/com/example/eeos/data/service/InfoService.kt
  AOS/app/src/main/java/com/example/eeos/data/source/InfoDataSource.kt
  AOS/app/src/main/java/com/example/eeos/domain/repository/InfoRepository.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavGraph.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetail.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetailViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/TopAppBarViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/util/GetErrorCode.kt
  AOS/gradle.properties
Labels: AOS
