Repository JNU-econovation/EEOS, pull requests merged in 2024-01, with the labels that each got.

#137 [AOS/FEAT] 행사 세부 화면 기능 구현
  AOS/.idea/misc.xml
  AOS/app/src/main/java/com/example/eeos/EEOSApplication.kt
  AOS/app/src/main/java/com/example/eeos/MainActivity.kt
  AOS/app/src/main/java/com/example/eeos/consts/Consts.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/request/RequestPutAttendStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponseGetAttendStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponseGetMemberListDto.kt
  AOS/app/src/main/java/com/example/eeos/data/repository/ProgramRepositoryImpl.kt
  AOS/app/src/main/java/com/example/eeos/data/service/ProgramService.kt
  AOS/app/src/main/java/com/example/eeos/data/source/ProgramDataSource.kt
  AOS/app/src/main/java/com/example/eeos/di/RetrofitModule.kt
  AOS/app/src/main/java/com/example/eeos/domain/model/AttendStatus.kt
  AOS/app/src/main/java/com/example/eeos/domain/model/Member.kt
  AOS/app/src/main/java/com/example/eeos/domain/repository/ProgramRepository.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavGraph.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/AttendStatusButtons.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/DetailScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberAttendanceViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberData.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberList.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetail.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetailViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusButton.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusButtons.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusChip.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusChips.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusInfo.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/BottomSheetContent.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/UserAttendStatusViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/confirmdialog/ConfirmAttendStatusDialog.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/ProgramLists.kt
  AOS/app/src/main/res/values/colors.xml
  AOS/app/src/main/res/values/dimension.xml
  AOS/app/src/main/res/values/strings.xml
Labels: AOS, feature☁️

#144 [FE/FEAT] API 로직 구현
  FE/src/apis/dtos/member.dto.ts
  FE/src/apis/dtos/program.dto.ts
  FE/src/apis/dtos/user.dto.ts
  FE/src/apis/instance.ts
  FE/src/apis/member.ts
  FE/src/apis/program.ts
  FE/src/apis/user.ts
  FE/src/constants/API.ts
  FE/src/constants/ROUTES.ts
  FE/src/hooks/useMemberQuery.ts
  FE/src/hooks/useProgramQuery.ts
  FE/src/hooks/useUserQuery.ts
Labels: FE, feature☁️

#148 [FE/FEAT] 행사 세부정보 페이지 구현
  FE/.eslintrc
  FE/package.json
  FE/pnpm-lock.yaml
  FE/public/icons/trash.svg
  FE/src/app/(program)/create/page.tsx
  FE/src/app/(program)/detail/[programId]/loading.tsx
  FE/src/app/(program)/detail/[programId]/page.tsx
  FE/src/app/(program)/edit/[programId]/page.tsx
  FE/src/app/globals.css
  FE/src/app/layout.tsx
  FE/src/app/main/loading.tsx
  FE/src/app/main/page.tsx
  FE/src/app/not-found.tsx
  FE/src/app/program/detail/page.tsx
  FE/src/components/common/Link.tsx
  FE/src/components/common/Title.tsx
  FE/src/components/common/attendStatusToggle/AttendStatusToggle.tsx
  FE/src/components/common/attendStatusToggle/AttendStatusToggleItem.tsx
  FE/src/components/common/header/CreateBtn.tsx
  FE/src/components/common/header/Logo.tsx
  FE/src/components/common/header/UserActiveModal.loader.tsx
  FE/src/components/common/header/UserActiveModal.tsx
  FE/src/components/common/header/UserBtn.tsx
  FE/src/components/common/markdown/MarkdownViewer.tsx
  FE/src/components/common/markdown/markdown-editor.styles.css
  FE/src/components/common/pagination/Pagination.tsx
  FE/src/components/common/pagination/PaginationItem.tsx
  FE/src/components/common/tabs/Tab.tsx
  FE/src/components/common/tabs/TextTab.tsx
  FE/src/components/main/ProgramList.tsx
  FE/src/components/main/ProgramListItem.tsx
  FE/src/components/programDetail/attendee/AttendeeInfo.loader.tsx
  FE/src/components/programDetail/attendee/AttendeeInfo.tsx
  FE/src/components/programDetail/attendee/AttendeeInfoContainer.tsx
  FE/src/components/programDetail/attendee/AttendeeStatus.tsx
  FE/src/components/programDetail/attendee/MemberList.tsx
  FE/src/components/programDetail/attendee/MemberListItem.tsx
  FE/src/components/programDetail/program/ProgramDetail.skeleton.tsx
  FE/src/components/programDetail/program/ProgramDetail.tsx
  FE/src/components/programDetail/program/ProgramHeader.skeleton.tsx
  FE/src/components/programDetail/program/ProgramHeader.tsx
  FE/src/components/programDetail/program/ProgramInfo.loader.tsx
  FE/src/components/programDetail/program/ProgramInfo.tsx
  FE/src/components/programDetail/userAttendModal/AttendStatusView.tsx
  FE/src/components/programDetail/userAttendModal/AttendToggleLabel.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
  FE/src/constants/ACTIVE_STATUS.ts
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/constants/MAIN.ts
  FE/src/constants/PROGRAM.ts
  FE/src/hooks/query/useProgramQuery.ts
  FE/src/hooks/query/useUserQuery.ts
  FE/src/storages/main.atom.ts
  FE/src/utils/provider.tsx
  FE/tsconfig.json
Labels: FE, feature☁️

#150 [FE/FEAT] 행사 생성 페이지 구현
  FE/src/app/(program)/create/loading.tsx
  FE/src/app/(program)/create/page.tsx
  FE/src/components/common/Button.tsx
  FE/src/components/common/CheckBox.tsx
  FE/src/components/common/calendar/Calendar.tsx
  FE/src/components/common/calendar/calendar.styles.css
  FE/src/components/common/form/FormBtn.tsx
  FE/src/components/common/form/LabeledInput.tsx
  FE/src/components/common/form/ProgramDate.tsx
  FE/src/components/common/form/ProgramDemandCheckBox.tsx
  FE/src/components/common/form/ProgramForm.tsx
  FE/src/components/common/form/ProgramTitle.tsx
  FE/src/components/common/markdown/MarkdownEditor.tsx
  FE/src/components/common/memberTable/MemberTable.tsx
  FE/src/components/common/memberTable/MemberTableHeader.tsx
  FE/src/components/programCreate/CreateMemberTableItem.tsx
  FE/src/components/programCreate/CreateMemberTableItemContainer.tsx
  FE/src/components/programCreate/ProgramCreateForm.tsx
  FE/src/components/programEdit/EditMemberTableItemContainer.tsx
  FE/src/constants/ACTIVE_STATUS.ts
  FE/src/constants/FORM_INFO.ts
  FE/src/hooks/useProgramFormData.ts
  FE/src/types/form.ts
  FE/src/utils/handleKeydown.ts
Labels: FE, feature☁️

#152 [FE/FEAT] 행사 수정 페이지 구현
  FE/src/app/(program)/edit/[programId]/loading.tsx
  FE/src/app/(program)/edit/[programId]/page.tsx
  FE/src/components/common/memberTable/MemberTable.tsx
  FE/src/components/common/memberTable/MemberTableHeader.tsx
  FE/src/components/programCreate/CreateMemberTableItem.tsx
  FE/src/components/programCreate/CreateMemberTableItemContainer.tsx
  FE/src/components/programCreate/ProgramCreateForm.tsx
  FE/src/components/programEdit/EditMemberTableItem.tsx
  FE/src/components/programEdit/EditMemberTableItemContainer.tsx
  FE/src/components/programEdit/ProgramEditForm.tsx
  FE/src/hooks/useProgramFormData.ts
Labels: FE, feature☁️

#159 [BE/FEAT] 멤버 활동 상태 기능 구현
  BE/eeos/resources/local-develop-environment/mysql-init.d/01_create_table.sql
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/DefaultCandidateService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/application/domain/token/TokenResolver.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/application/exception/AuthorizationException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/application/exception/InvalidTokenException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/application/exception/NotFoundHeaderTokenException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/application/exception/TokenExpiredException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/presentation/LoginConfig.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/presentation/interceptor/AuthInterceptor.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/presentation/support/HeaderTokenExtractor.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/presentation/support/Member.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/presentation/support/MemberArgumentResolver.java
  BE/eeos/src/main/java/com/blackcompany/eeos/config/WebMvcConfig.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/QueryMembersResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/dto/ChangeActiveStatusRequest.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/dto/CommandMemberResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/dto/QueryMemberResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/dto/converter/CommandMemberResponseConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/dto/converter/QueryMemberResponseConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/exception/NotFoundActiveStatusException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/exception/NotFoundMemberException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/model/ActiveStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/model/MemberModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/model/converter/MemberEntityConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/service/CommandMemberService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/service/MemberService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/service/QueryMemberService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/support/ActiveStatusSupplier.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/usecase/ChangeActiveStatusUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/usecase/GetMemberByActiveStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/usecase/GetMembersByActiveStatus.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/presentation/controller/CommandMemberController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/presentation/controller/QueryMemberController.java
  BE/eeos/src/test/java/com/blackcompany/eeos/member/application/model/ActiveStatusTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/member/application/model/MemberModelTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/member/application/service/CommandMemberServiceTest.java
  BE/eeos/src/test/java/com/blackcompany/eeos/member/fixture/FakeMember.java
Labels: BE, feature☁️

#154 [FE/FEAT] Member Table 로직 수정하기
  FE/src/app/main/page.tsx
  FE/src/components/common/attendStatusToggle/AttendStatusToggle.tsx
  FE/src/components/common/form/ProgramForm.tsx
  FE/src/components/common/memberTable/MemberTable.tsx
  FE/src/components/common/memberTable/MemberTableHeader.tsx
  FE/src/components/main/ProgramList.tsx
  FE/src/components/programCreate/CreateMemberTableItemContainer.tsx
  FE/src/components/programCreate/ProgramCreateForm.tsx
  FE/src/components/programEdit/EditMemberTableItem.tsx
  FE/src/components/programEdit/EditMemberTableItemContainer.tsx
  FE/src/components/programEdit/ProgramEditForm.tsx
  FE/src/hooks/query/useProgramQuery.ts
  FE/src/hooks/useProgramFormData.ts
Labels: FE, feature☁️

#166 [FE/FEAT] 기능명세서에서 놓친 기능 구현
  FE/src/components/common/form/ProgramForm.tsx
  FE/src/components/common/header/UserActiveModal.tsx
  FE/src/components/common/memberTable/MemberTable.tsx
  FE/src/components/programCreate/ProgramCreateForm.tsx
  FE/src/components/programDetail/attendee/AttendeeInfo.tsx
  FE/src/components/programDetail/userAttendModal/AttendStatusView.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
  FE/src/components/programEdit/EditMemberTableItem.tsx
  FE/src/components/programEdit/EditMemberTableItemContainer.tsx
  FE/src/components/programEdit/ProgramEditForm.tsx
  FE/src/constants/ALERT.ts
  FE/src/hooks/query/useProgramQuery.ts
  FE/src/hooks/query/useUserQuery.ts
  FE/src/hooks/useProgramFormData.ts
Labels: FE, feature☁️

#171 [BE/FEAT] 프로그램 추가 요구사항 구현
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/QueryAccessRightResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/QueryProgramResponse.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/converter/ProgramPageResponseConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/converter/ProgramResponseConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/dto/converter/QueryAccessRightResponseConverter.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/model/AccessRights.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetAccessRightUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetProgramUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/usecase/GetProgramsUsecase.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
  BE/eeos/src/main/resources/env.properties
Labels: BE, feature☁️

#174 [FE/FEAT] 페이지 접근 권한 구현
  FE/src/apis/dtos/program.dto.ts
  FE/src/apis/program.ts
  FE/src/app/(private)/(program)/edit/[programId]/page.tsx
  FE/src/app/(private)/(program)/layout.tsx
  FE/src/app/(private)/(program)/main/page.tsx
  FE/src/app/(private)/layout.tsx
  FE/src/components/common/validate/AccessRight.tsx
  FE/src/components/common/validate/Auth.tsx
  FE/src/components/programDetail/attendee/AttendeeInfo.tsx
  FE/src/components/programDetail/program/EditAndDeleteButton.tsx
  FE/src/components/programDetail/program/ProgramHeader.tsx
  FE/src/constants/ALERT.ts
  FE/src/constants/API.ts
  FE/src/hooks/query/useProgramQuery.ts
  FE/src/types/program.ts
Labels: FE, feature☁️

#176 [FE/FEAT] 요청 결과 Alert 창 구현
  FE/package.json
  FE/pnpm-lock.yaml
  FE/src/apis/program.ts
  FE/src/apis/user.ts
  FE/src/components/common/header/Modal/ActiveStatusTab.tsx
  FE/src/components/common/validate/AccessRight.tsx
  FE/src/components/programDetail/program/EditAndDeleteButton.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
  FE/src/components/programEdit/EditMemberTableItem.tsx
  FE/src/constants/ALERT.ts
  FE/src/constants/MESSAGE.ts
  FE/src/utils/authWithStorage.ts
  FE/src/utils/provider.tsx
Labels: FE, feature☁️

#182 [FE/HOT-FIX] 배포 후 버그 해결
  FE/package.json
  FE/pnpm-lock.yaml
  FE/public/icons/error.svg
  FE/public/saly-run.svg
  FE/src/apis/auth.ts
  FE/src/apis/dtos/auth.dto.ts
  FE/src/apis/dtos/member.dto.ts
  FE/src/apis/dtos/program.dto.ts
  FE/src/apis/dtos/user.dto.ts
  FE/src/apis/instance.ts
  FE/src/apis/member.ts
  FE/src/apis/program.ts
  FE/src/apis/user.ts
  FE/src/app/(auth)/login/logging-in/page.tsx
  FE/src/app/(private)/(program)/detail/[programId]/page.tsx
  FE/src/app/(private)/(program)/detail/error.tsx
  FE/src/app/(private)/(program)/detail/loading.tsx
  FE/src/app/(private)/(program)/edit/[programId]/page.tsx
  FE/src/app/(private)/(program)/edit/error.tsx
  FE/src/app/(private)/(program)/edit/loading.tsx
  FE/src/app/(private)/(program)/main/page.tsx
  FE/src/app/not-found.tsx
  FE/src/components/common/Button.tsx
  FE/src/components/common/ErrorFallback.tsx
  FE/src/components/common/ErrorFallbackNoIcon.tsx
  FE/src/components/common/Title.tsx
  FE/src/components/common/header/Modal/UserActiveModal.loader.tsx
  FE/src/components/common/header/Modal/UserActiveModal.tsx
  FE/src/components/common/header/Modal/UserInfoSection.tsx
  FE/src/components/common/header/UserBtn.tsx
  FE/src/components/common/memberTable/MemberTable.loader.tsx
  FE/src/components/common/memberTable/MemberTable.tsx
  FE/src/components/common/memberTable/MemberTableItem.loader.tsx
  FE/src/components/common/validate/AccessRight.tsx
  FE/src/components/login/slack/LoginButton.tsx
  FE/src/components/main/ProgramList.tsx
  FE/src/components/programCreate/CreateMemberTableItemContainer.tsx
  FE/src/components/programDetail/attendee/AttendeeInfo.tsx
  FE/src/components/programDetail/attendee/AttendeeInfoContainer.tsx
  FE/src/components/programDetail/program/ProgramHeader.tsx
  FE/src/components/programDetail/userAttendModal/AttendStatusModal.loader.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.container.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
  FE/src/components/programEdit/EditMemberTableItemContainer.tsx
  FE/src/constants/API.ts
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/constants/ERROR_CODE.ts
  FE/src/constants/ERROR_MESSAGE.ts
  FE/src/constants/NOT_FOUND.ts
  FE/src/hooks/query/useAuthQuery.ts
  FE/src/hooks/query/useMemberQuery.ts
  FE/src/hooks/query/useProgramQuery.ts
  FE/src/hooks/query/useUserQuery.ts
  FE/src/types/member.ts
  FE/src/utils/provider.tsx
Labels: FE, bug-fix🚨

#186 [FE\FEAT] Auth 관련 에러 핸들링 로직 추가
  FE/src/apis/instance.ts
  FE/src/app/(private)/(program)/detail/error.tsx
  FE/src/app/(private)/(program)/edit/error.tsx
  FE/src/components/common/validate/AccessRight.tsx
  FE/src/constants/ERROR_CODE.ts
  FE/src/constants/ERROR_MESSAGE.ts
  FE/src/utils/authWithStorage.ts
Labels: FE, feature☁️

#188 [AOS/FEAT] 로그인 관련 기능 구현
  .github/workflows/eeos-android-ci.yml
  AOS/app/build.gradle
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/com/example/eeos/EEOSApplication.kt
  AOS/app/src/main/java/com/example/eeos/MainActivity.kt
  AOS/app/src/main/java/com/example/eeos/consts/Consts.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/request/RequestPutActiveStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/request/RequestPutAttendStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponsePostLoginDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponsePutActiveStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponsePutAttendStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponseReIssueTokenDto.kt
  AOS/app/src/main/java/com/example/eeos/data/repository/AuthRepositoryImpl.kt
  AOS/app/src/main/java/com/example/eeos/data/service/AuthService.kt
  AOS/app/src/main/java/com/example/eeos/data/service/ProgramService.kt
  AOS/app/src/main/java/com/example/eeos/data/source/AuthDataSource.kt
  AOS/app/src/main/java/com/example/eeos/di/RepositoryModule.kt
  AOS/app/src/main/java/com/example/eeos/di/RetrofitModule.kt
  AOS/app/src/main/java/com/example/eeos/di/ServiceModule.kt
  AOS/app/src/main/java/com/example/eeos/domain/repository/AuthRepository.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavGraph.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavigation.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/DetailScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberAttendanceViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberList.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetailViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusButtons.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusChips.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/BottomSheetContent.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/UserAttendStatusViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/ProgramLists.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/theme/Theme.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/ActiveStatusButtons.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/ActiveStatusDialog.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/EeosTopAppBar.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/TopAppBarViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/util/GetDateTime.kt
  AOS/app/src/main/java/com/example/eeos/presentation/util/Preference.kt
  AOS/app/src/main/res/drawable/btn_add_to_slack_4000x1172_d770e0c.png
  AOS/app/src/main/res/values/dimension.xml
  AOS/app/src/main/res/values/strings.xml
Labels: AOS, feature☁️

#189 aos merge to main
  .github/workflows/eeos-android-ci.yml
  AOS/app/build.gradle
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/com/example/eeos/EEOSApplication.kt
  AOS/app/src/main/java/com/example/eeos/MainActivity.kt
  AOS/app/src/main/java/com/example/eeos/consts/Consts.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/request/RequestPutActiveStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/request/RequestPutAttendStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponsePostLoginDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponsePutActiveStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponsePutAttendStatusDto.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponseReIssueTokenDto.kt
  AOS/app/src/main/java/com/example/eeos/data/repository/AuthRepositoryImpl.kt
  AOS/app/src/main/java/com/example/eeos/data/service/AuthService.kt
  AOS/app/src/main/java/com/example/eeos/data/service/ProgramService.kt
  AOS/app/src/main/java/com/example/eeos/data/source/AuthDataSource.kt
  AOS/app/src/main/java/com/example/eeos/di/RepositoryModule.kt
  AOS/app/src/main/java/com/example/eeos/di/RetrofitModule.kt
  AOS/app/src/main/java/com/example/eeos/di/ServiceModule.kt
  AOS/app/src/main/java/com/example/eeos/domain/repository/AuthRepository.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavGraph.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavigation.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/DetailScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberAttendanceViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberList.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetailViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusButtons.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusChips.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/BottomSheetContent.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/UserAttendStatusViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/ProgramLists.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/theme/Theme.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/ActiveStatusButtons.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/ActiveStatusDialog.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/EeosTopAppBar.kt
  AOS/app/src/main/java/com/example/eeos/presentation/topappbar/TopAppBarViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/util/GetDateTime.kt
  AOS/app/src/main/java/com/example/eeos/presentation/util/Preference.kt
  AOS/app/src/main/res/drawable/btn_add_to_slack_4000x1172_d770e0c.png
  AOS/app/src/main/res/values/dimension.xml
  AOS/app/src/main/res/values/strings.xml
Labels: AOS, feature☁️

#195 [BE/FIX] 종료된 프로그램 참석 정보 수정 가능하도록 변경
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/AttendModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/AttendTargetService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/SelectAttendTargetService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/persistence/AttendEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/persistence/AttendRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/presentation/controller/AuthController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/presentation/support/CookieTokenExtractor.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/application/model/MemberIdModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/persistence/MemberIdEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/exception/NotFoundMemberException.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/model/MemberModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/model/ProgramModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/service/ProgramService.java
Labels: BE, bug-fix🚨

#196 [BE/FIX] attend 도메인 리팩터링
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/model/AttendModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/SelectAttendTargetService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/persistence/AttendEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/presentation/AttendController.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/persistence/AuthInfoRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/persistence/OauthInfoRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/application/model/MemberIdModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/application/model/MemberModel.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberRepository.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/persistence/ProgramEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/presentation/ProgramController.java
Labels: BE, bug-fix🚨, enhancement 🍀

#197 [AOS/FEAT] 로그인 에러 처리
  AOS/app/build.gradle
  AOS/app/src/main/java/com/example/eeos/consts/Consts.kt
  AOS/app/src/main/java/com/example/eeos/consts/ErrorCode.kt
  AOS/app/src/main/java/com/example/eeos/data/interceptor/AddHeaderInterceptor.kt
  AOS/app/src/main/java/com/example/eeos/data/interceptor/GetRefreshInterceptor.kt
  AOS/app/src/main/java/com/example/eeos/data/interceptor/Qualifier.kt
  AOS/app/src/main/java/com/example/eeos/data/repository/AuthRepositoryImpl.kt
  AOS/app/src/main/java/com/example/eeos/data/service/AuthService.kt
  AOS/app/src/main/java/com/example/eeos/data/source/AuthDataSource.kt
  AOS/app/src/main/java/com/example/eeos/di/RetrofitModule.kt
  AOS/app/src/main/java/com/example/eeos/domain/repository/AuthRepository.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavGraph.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberAttendanceViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetailViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/UserAttendStatusViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginErrorScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginLoadingScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginOriginScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginViewModel.kt
  AOS/app/src/main/res/drawable/common_logo_icon.xml
  AOS/app/src/main/res/values/dimension.xml
Labels: AOS, feature☁️

#200 [FE/HOTFIX] 연결 시 발생한 에러를 해결합니다.
  FE/src/apis/instance.ts
  FE/src/app/(auth)/login/name-error/page.tsx
  FE/src/app/(private)/(program)/edit/[programId]/page.tsx
  FE/src/components/common/ErrorFallback.tsx
  FE/src/components/common/attendStatusToggle/AttendStatusToggleItem.tsx
  FE/src/components/common/form/ProgramForm.tsx
  FE/src/components/common/form/ProgramTitle.tsx
  FE/src/components/common/header/Logo.tsx
  FE/src/components/common/header/UserBtn.tsx
  FE/src/components/common/markdown/MarkdownEditor.tsx
  FE/src/components/common/markdown/MarkdownViewer.tsx
  FE/src/components/common/pagination/Pagination.tsx
  FE/src/components/common/pagination/PaginationItem.tsx
  FE/src/components/common/tabs/TabItem.tsx
  FE/src/components/common/tabs/TextTab.tsx
  FE/src/components/programCreate/CreateMemberTableItem.tsx
  FE/src/components/programCreate/ProgramCreateForm.tsx
  FE/src/components/programDetail/program/EditAndDeleteButton.tsx
  FE/src/components/programDetail/userAttendModal/AttendToggleLabel.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.container.tsx
  FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
  FE/src/components/programEdit/EditMemberTableItem.tsx
  FE/src/components/programEdit/EditMemberTableItemContainer.tsx
  FE/src/components/programEdit/ProgramEditForm.tsx
  FE/src/constants/ATTEND_STATUS.ts
  FE/src/constants/ERROR_CODE.ts
  FE/src/constants/ERROR_MESSAGE.ts
  FE/src/constants/ROUTES.ts
  FE/src/hooks/query/useAuthQuery.ts
  FE/src/hooks/query/useProgramQuery.ts
  FE/src/hooks/useOutsideRef.ts
  FE/src/hooks/useProgramFormData.ts
  FE/src/types/attendStatusModal.ts
  FE/src/utils/convert.ts
Labels: FE, bug-fix🚨

#205 [BE/FEAT] 로그 설정
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/application/service/CommandAttendService.java
  BE/eeos/src/main/java/com/blackcompany/eeos/common/exception/GlobalExceptionHandler.java
  BE/eeos/src/main/java/com/blackcompany/eeos/program/application/event/DeletedProgramEventListener.java
  BE/eeos/src/main/resources/application-local-mysql.yml
  BE/eeos/src/main/resources/application-mysql.yml
  BE/eeos/src/main/resources/logback-spring.xml
  BE/eeos/src/main/resources/logback-variables.properties
Labels: BE, feature☁️

#206 [BE/FEAT] 데이터 마이그레이션을 위한 flyway 설정
  BE/eeos/build.gradle
  BE/eeos/docker-compose.yml
  BE/eeos/src/main/java/com/blackcompany/eeos/attend/persistence/AttendEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/auth/persistence/AuthInfoEntity.java
  BE/eeos/src/main/java/com/blackcompany/eeos/member/persistence/MemberEntity.java
  BE/eeos/src/main/resources/application-local-mysql.yml
  BE/eeos/src/main/resources/application-mysql.yml
  BE/eeos/src/main/resources/db/migration/V00__init__table.sql
  BE/eeos/src/main/resources/db/migration/V01__alter_table.sql
  BE/eeos/src/main/resources/db/migration/V02__add_table.sql
Labels: BE, feature☁️

#211 [FE/FIX] checkbox 에러 해결
  FE/src/components/common/memberTable/MemberTableHeader.tsx
  FE/src/components/programCreate/CreateMemberTableItemContainer.tsx
  FE/src/store/memberTableCheckedAtom.ts
Labels: FE, bug-fix🚨

#212 [FE/HOTFIX] 체크박스 에러 해결
  FE/src/components/common/memberTable/MemberTableHeader.tsx
  FE/src/components/programCreate/CreateMemberTableItemContainer.tsx
  FE/src/store/memberTableCheckedAtom.ts
Labels: FE, bug-fix🚨

#213 [FE/FIX] 체크박스 해제 시 모든 멤버가 취소되는 문제 해결
  FE/src/components/programCreate/ProgramCreateForm.tsx
Labels: FE, bug-fix🚨

#214 [FE/HOTFIX] 체크박스 해제 시 다른 상태에도 영향끼치는 문제 해결
  FE/src/components/programCreate/ProgramCreateForm.tsx
Labels: FE, bug-fix🚨

#218 hotfix: NAME_MANUAL_URL 수정 및 .env 파일에서 관리
  FE/src/app/(auth)/login/name-error/page.tsx
Labels: FE, bug-fix🚨

#219 hotfix: NAME MANUAL URL 수정 및 .env에서 관리
  FE/src/app/(auth)/login/name-error/page.tsx
Labels: FE, bug-fix🚨

#224 [AOS/FEAT] 운영용 URL 적용 및 행사 종료 시 참석 상태 수정 불가 설정
  .github/workflows/eeos-android-ci.yml
  AOS/app/build.gradle
  AOS/app/src/main/java/com/example/eeos/consts/Consts.kt
  AOS/app/src/main/java/com/example/eeos/consts/ErrorCode.kt
  AOS/app/src/main/java/com/example/eeos/data/interceptor/AddHeaderInterceptor.kt
  AOS/app/src/main/java/com/example/eeos/data/interceptor/GetRefreshInterceptor.kt
  AOS/app/src/main/java/com/example/eeos/data/interceptor/Qualifier.kt
  AOS/app/src/main/java/com/example/eeos/data/model/remote/response/ResponseGetProgramDetailDto.kt
  AOS/app/src/main/java/com/example/eeos/data/repository/AuthRepositoryImpl.kt
  AOS/app/src/main/java/com/example/eeos/data/service/AuthService.kt
  AOS/app/src/main/java/com/example/eeos/data/source/AuthDataSource.kt
  AOS/app/src/main/java/com/example/eeos/di/RetrofitModule.kt
  AOS/app/src/main/java/com/example/eeos/domain/model/ProgramDetail.kt
  AOS/app/src/main/java/com/example/eeos/domain/repository/AuthRepository.kt
  AOS/app/src/main/java/com/example/eeos/navigation/EEOSNavGraph.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/MemberAttendanceViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/ProgramDetailViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/AttendStatusButtons.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/BottomSheetContent.kt
  AOS/app/src/main/java/com/example/eeos/presentation/detail/bottomsheet/UserAttendStatusViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/home/HomeViewModel.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginErrorScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginLoadingScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginOriginScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginScreen.kt
  AOS/app/src/main/java/com/example/eeos/presentation/login/LoginViewModel.kt
  AOS/app/src/main/res/drawable/common_logo_icon.xml
  AOS/app/src/main/res/values/dimension.xml
  AOS/app/src/main/res/values/strings.xml
Labels: AOS, feature☁️

#229 [AOS/SETTING] gitignore 파일 수정 및 debugKey 설정
  AOS/.gitignore
  AOS/.idea/deploymentTargetDropDown.xml
  AOS/app/build.gradle
  AOS/app/src/main/AndroidManifest.xml
  AOS/gradle.properties
Labels: AOS, setting ⚙️
